services:
  flaskapp:
    build:
      context: ./backend
    image: flaskapp
    depends_on:
      - mysqldb
    restart: unless-stopped
    expose:
      - '5000'
    volumes:
      - flaskapp-static:/src/flaskapp/static
    networks:
      - frontend-network
      - backend-network
    environment:
      SESSION_KEY: ${SESSION_KEY}
      MYSQL_HOST: mysqldb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      S3_URL: minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

  nginx:
    build:
      context: ./nginx
    image: flaskapp-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - flaskapp-static:/static
    networks:
      - frontend-network

  minio:
    image: minio/minio
    restart: unless-stopped
    expose:
      - '9000'
    volumes:
      - minio-storage:/data
    networks:
      - frontend-network
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: ['server', '/data']

  mysqldb:
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql
    networks:
      - backend-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
  mysql-config:
  flaskapp-static:
  minio-storage:

networks:
  frontend-network:
  backend-network:
