services:
  flaskapp:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/src
    environment:
      FLASK_ENV: development
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: devdbpass
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql

volumes:
  mysql-data:
  mysql-config:
